name: crypto_cent
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  curved_navigation_bar: ^1.0.3
#  flutter_slidable: ^2.0.0
  flutter_slidable: ^1.3.0
  fluttertoast: ^8.0.9
  percent_indicator: ^4.0.1
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.1
  icons_launcher: ^1.1.8
  country_code_picker: ^2.0.2
  syncfusion_flutter_datepicker: ^20.1.55
  country_picker: ^2.0.15
#  bloc: ^8.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1

  ### Google SignIn
  google_sign_in: ^5.4.0
  firebase_auth: ^3.3.17
  firebase_core: ^1.21.1
  firebase_messaging: ^10.0.0

  ### Facebook Login
  flutter_facebook_auth: ^4.4.0
  flutter_signin_button: ^2.0.0
  ### Google Icon
  font_awesome_flutter: ^9.0.0
  ### State Management
  provider: ^5.0.0
  get: ^4.6.5
  ### check connectivity
  connectivity:

  lottie: ^1.3.0
  url_launcher: ^6.1.5
  map_launcher: ^2.3.0+1
  image_picker: ^0.8.4
#  multi_image_picker: ^4.8.1
  multi_image_picker:
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  open_mail_app: ^0.4.5
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^3.5.1
  uuid: ^3.0.6
  qr_flutter: ^4.0.0


flutter_icons:
  image_path: 'assets/images/wel.png'
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/video/
    - .env

  
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
